// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repositories.EFCore;

#nullable disable

namespace Repositories.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    partial class RepositoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Entities.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<double>("Price")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(10.0);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Price = 89.0,
                            Title = "Things Fall Apart "
                        },
                        new
                        {
                            Id = 2,
                            Price = 25.0,
                            Title = "Night"
                        },
                        new
                        {
                            Id = 3,
                            Price = 45.0,
                            Title = "The Kite Runner"
                        },
                        new
                        {
                            Id = 4,
                            Price = 55.0,
                            Title = "The Stranger"
                        },
                        new
                        {
                            Id = 5,
                            Price = 95.0,
                            Title = "Cry, the Beloved Country"
                        },
                        new
                        {
                            Id = 6,
                            Price = 35.0,
                            Title = "Metamorphosis"
                        },
                        new
                        {
                            Id = 7,
                            Price = 78.0,
                            Title = "The Odyssey "
                        },
                        new
                        {
                            Id = 8,
                            Price = 85.0,
                            Title = "Candide"
                        },
                        new
                        {
                            Id = 9,
                            Price = 96.0,
                            Title = "Illiad"
                        },
                        new
                        {
                            Id = 10,
                            Price = 98.0,
                            Title = "Life of Pi"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
